### PR TITLE
Make CSI --kubelet-registration-path configurable in the Helm chart

### PR DESCRIPTION
**Pull request by rkrzewski**

### CODE REVIEW

**Comment by rkrzewski** [comment]
As you can see in #406 I had to override a bunch of paths to get the `topolvm-node` component to behave on microk8s.

Maybe introducing a single setting like `node.kubeletWorkDirectory` with default value of `/var/log/kubelet` that could be overriden to `/var/snap/microk8s/common/var/log/kubelet` or even setting `node.microk8s` with default value of `false` that would switch between those paths would be a better idea? Or both? Let me know, I'll update the PR.

**Comment by toshipp** [comment]
As you say, it may be better to introduce `node.kubeletWorkDirectory`, but we chose to introduce parameters for volumes and volumeMounts for flexibility. If introducing the parameter, they conflict with each other and it may confuse users, so keeping your current implementation is better than that, IMO.
For `node.microk8s`, I think it is not needed because your PR is sufficient for the issue, and it breaks simplicity if introducing it.

**Comment by toshipp** [comment]
Could you update `charts/topolvm/README.md` by executing `./bin/helm-docs`?

**Comment by rkrzewski** [comment]
I've updated documentation as requested.

**Comment by rkrzewski** [comment]
I'm pondering the possible configuration options, and it think it would be preferable to:
- introduce `node.kubeletWorkDirectory` parameter
- move the contents of `node.volumes` and `node.volumeMounts.topolvmNode` to `templates/node/deamonset.yaml` and replace `/var/lib/kubelet/` prefix in the paths with `node.kubeletWorkDirectory` parameters
- initialize `node.volumes` and `node.volumeMounts.topolvmNode` with value of `{}` in `values.yaml` and add logic to `templates/node/deamonset.yaml` use them for overriding default configuration them if necessary.

This would allow the following benefits:
- It would do the right thing in the default case of `/var/lib/kubelet` work directory
- Deploying on microk8s would require overriding a single parameter instead of a large chunk yaml (see #406)
- In the case that overriding individual paths is necessary it still can be done by overriding `node.volumes` and `node.volumeMounts.topolvmNode` however my understanding is that it should not be necessary. These paths need to change together for the integration to work: both kubelet and CSI sidecars need to see the same data under the same paths for the commands to be processed correctly.

I realize that it's a bit of an intrusive change, especially that there are more components that have their mounts declared via `values.yaml` besides node deaemonset, so I am waiting for your opinion before proceeding.

**Comment by toshipp** [comment]
It looks good. Anyway, it is not just a refactoring but adding a feature, so would you separate it from this PR if you proceed?

**Comment by rkrzewski** [comment]
I'll open a separate PR, because it'll be an alternative solution to the same problem. If you accept the other one, this PR can be discarded.

**Comment by daichimukai** [comment]
An alternative solution #410 is merged. Close this.

**Pull request closed without merging**
