### PR TITLE
remove empty lines from generated manifests

### PR DESCRIPTION
**Pull request by jurim76**
Remove unnecessary blank lines from helm generated manifests.

### CODE REVIEW

**Comment by ushitora-anqou** [comment]
Hi! Could you sign off your commit? Thanks!

See also: https://github.com/topolvm/topolvm/blob/main/CONTRIBUTING.md#sign-your-commits

**Comment by jurim76** [comment]
> Hi! Could you sign off your commit? Thanks!
Hello @ushitora-anqou 
Should be signed off, please check

**Review by jakobmoellerdev — APPROVED** [review]
LGTM

**Review by ushitora-anqou — APPROVED** [review]

**Comment by ushitora-anqou** [comment]
Thank you for your contribution!

**Pull request merged**
