### PR TITLE
Change base image to standard ubuntu.

### LINKED ISSUE #197: base image
**Describe the bug**
Is there a reason to base the container FROM quay.io/cybozu/ubuntu:18.04 rather then the official ubuntu?

As its a go based build, would alpine or distroless be even better (smaller)?

### PR DESCRIPTION
**Pull request by llamerada-jp**
Resolves #197 

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

### CODE REVIEW

**Review by ymmt2005 — DISMISSED** [review]
LGTM

**Review by zoetrope — COMMENTED** [review]
I found some `quay.io/cybozu/ubuntu`.

https://github.com/topolvm/topolvm/search?q=%22quay.io%2Fcybozu%2Fubuntu%22&unscoped_q=%22quay.io%2Fcybozu%2Fubuntu%22

Do you need to fix these?

**Comment by ymmt2005** [comment]
@llamerada-jp please just drop the last two commits.
Use `git rebase -i HEAD~~~` and remove the last two.

**Review by ymmt2005 — APPROVED** [review]
LGTM

**Review by zoetrope — APPROVED** [review]
LGTM

**Pull request merged**
