### PR TITLE
Add support to create PVC-PVC Clones for thin volumes

### PR DESCRIPTION
**Pull request by Yuggupta27**
For PVCs backed by thin-volumes, users will now be able to create
PVC-PVC clones.
Also, added deployment of PVC-Clone to the example setup.

### CODE REVIEW

**Comment by Yuggupta27** [comment]
> We want to keep the example as simple as possible, so would you please remove the example of clone feature? Instead of that, would you add an example of datasource in `user-manual.md`?

@llamerada-jp Sure, I agree. Instead of adding it to the example deployment, we can make it a part of the already existing [design doc](https://github.com/topolvm/topolvm/pull/447) where we can explain its usage.

> Clone feature can be used with only a thin pool, aren't you? example environment is using a thick pool, so the example of this  PR isn't runnable. If you can run it, it may make a thin snapshot in a thick pool. Would you check it because that is unexpected behavior?

In a previous PR, we added support to [create a thin pool](https://github.com/topolvm/topolvm/pull/467/files#diff-a7f0749bdafe7d4247c8435bbb139a3ca42c20bf58a96868ac286419afb764d1R91) in the example cluster, and also updated the `podpvc.yaml` to create a `thin` PVC along with a thick one([See](https://github.com/topolvm/topolvm/pull/467/files#diff-8b57ea8aa84aceada091ad93b91c3acc786aeb3d5eea6f7013d05325b6880cfdR33-R66)). With the added example deployment for [PVC-Clone](https://github.com/topolvm/topolvm/pull/498/commits/3352ff782b331582e5a218cdd2dcc3db3162426e), we are creating a PVC-PVC Clone, from already existing `thin` PVC.
Thus, as a result, we are creating a thin-snapshot (internally for clone) out of a thin parent volume.

> About the e2e test, are you planning to update it in another PR the same as a snapshot?

Since e2e for snapshot is also pending, keeping in mind the strict timelines, we have planned to add all the e2e in a separate PR (As majority of helper functions will be same for restore as for clone; so easier to add everything at once,)
In meantime, just added the deployment of PVC-Clone from a thin-parent-PVC in the example cluster, to demonstrate the successful working of the feature(Which we can get rid of if you suggest).

**Comment by llamerada-jp** [comment]
> we can make it a part of the already existing https://github.com/topolvm/topolvm/pull/447 where we can explain its usage.

Sure. Let's go with that idea.

> In a previous PR, we added support to [create a thin pool](https://github.com/topolvm/topolvm/pull/467/files#diff-a7f0749bdafe7d4247c8435bbb139a3ca42c20bf58a96868ac286419afb764d1R91) in the example cluster

I missed it. The behavior of example in this PR is normal. Thank you.

> Since e2e for snapshot is also pending, keeping in mind the strict timelines, we have planned to add all the e2e in a separate PR (As majority of helper functions will be same for restore as for clone; so easier to add everything at once,)

I understand. Let's go ahead with that plan.

> In meantime, just added the deployment of PVC-Clone from a thin-parent-PVC in the example cluster, to demonstrate the successful working of the feature(Which we can get rid of if you suggest).

We would like to ask you to delete the changes to the example.

And I'm going to check several behaviors today.

**Comment by Yuggupta27** [comment]
> We would like to ask you to delete the changes to the example.

Thanks for the review! Updated :+1:

**Review by llamerada-jp — APPROVED** [review]
I checked serval behavior. The behavior is in accordance with the specification, but the following patterns need attention.
- Make origin PVC and Pod.
- Make clone PVC and pod with podAffinity.
- Delete origin PVC and Pod.
- After deleting the origin Pod, the cloned pod can not restart because the cloned pod can not satisfy podAffinity.

To avoid this issue, we shouldn't delete origin pod or should use nodeAffinity instead of podAffinity. There is no problem with this PR, but it's better to add a note to the documentation.

**Comment by Yuggupta27** [comment]
> I checked serval behavior. The behavior is in accordance with the specification, but the following patterns need attention.
> 
> * Make origin PVC and Pod.
> * Make clone PVC and pod with podAffinity.
> * Delete origin PVC and Pod.
> * After deleting the origin Pod, the cloned pod can not restart because the cloned pod can not satisfy podAffinity.
> 
> To avoid this issue, we shouldn't delete origin pod or should use nodeAffinity instead of podAffinity. There is no problem with this PR, but it's better to add a note to the documentation.

Thanks @llamerada-jp for verifying! Will add the notes in the document PR https://github.com/topolvm/topolvm/pull/447 once this PR is merged.

**Review by cupnes — APPROVED** [review]
LGTM

**Pull request merged**
