### PR TITLE
charts: Deprecated PodSecurityPolicy API Migration

### PR DESCRIPTION
**Pull request by duanhongyi**

### CODE REVIEW

**Comment by duanhongyi** [comment]
@daichimukai
https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125

This API was marked deprecated from 1.21 and will be removed at 1.25

**Comment by daichimukai** [comment]
@duanhongyi 
We know that and had already deprecated PodSecurityPolicy.
https://github.com/topolvm/topolvm#deprecated-features

I am not sure why changing the apiVersion of PodSecurityPolicy from `policy/v1beta1` to `policy/v1` makes sense as a migration.

**Comment by duanhongyi** [comment]
I see. Sorry, I didn't see https://github.com/topolvm/topolvm#deprecated-features. Indeed, this PR is unnecessary.

**Comment by daichimukai** [comment]
@duanhongyi 
No problem at all. Please feel free to open an issue or PR if noticed anything :)

**Pull request closed without merging**
