### PR TITLE
Add support for ECS logging

### PR DESCRIPTION
**Pull request by kvalliyurnatt**
Add support for logging in ECS format so that the topolvm logs can be ingested by Elasticsearch

### CODE REVIEW

**Comment by toshipp** [comment]
Hi,
Thank you for your contribution. I've reviewed it and am concerned about introducing vendor-specific logic into TopoLVM. I would prefer this to be implemented as a more generic feature.

**Comment by jakobmoellerdev** [comment]
@kvalliyurnatt do you want to rewrite this into a more generic logging adaptor or should we close this one out?

**Comment by kvalliyurnatt** [comment]
@jakobmoellerdev I will work on making this more generic, sorry haven't gotten to this in a while. Will try to tackle this in the next couple of weeks.

**Comment by kvalliyurnatt** [comment]
CLosing this as we currently are unable to make progress on this

**Pull request closed without merging**
