### PR TITLE
Remove kustomize.

### PR DESCRIPTION
**Pull request by d-kuro**
refs: https://github.com/topolvm/topolvm/issues/297

### CODE REVIEW

**Comment by toshipp** [comment]
Would you delete this statement from top level README?
> For production deployments, see deploy directory.

**Comment by toshipp** [comment]
Although I found that other statements referring to kustomize in `RELEASE.md` and `docs/maintenance.md`, this related to maintainer tasks, so just leave it.

**Comment by d-kuro** [comment]
@toshipp

Thanks! I updated docs:
https://github.com/topolvm/topolvm/pull/336/commits/8393ea937ec0f4d67975e2066f15f24e67c0665a
https://github.com/topolvm/topolvm/pull/336/commits/4ecf4378b8ff62af5569072c4ab3ea0f3a96a216
https://github.com/topolvm/topolvm/pull/336/commits/9130fc3e94d1f94f4067a7601efffe65e8c2cd48

**Review by toshipp — APPROVED** [review]

**Review by llamerada-jp — APPROVED** [review]
LGTM

**Pull request merged**
